site_name: HUST开源计划
site_url: https://github.com/YuhangChen1/HUST_OPEN_SOURCE
site_author: Francis_Chen
site_description: >-
  HUST开源计划

repo_name: HUST_OPEN_SOURCE
repo_url: https://github.com/YuhangChen1/HUST_OPEN_SOURCE

copyright: Copyright &copy; 2025-present <a href="https://github.com/YuhangChen1/" target="_blank" rel="noopener noreferrer">YuhangChen1/a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  # favicon: images/favicon.ico
  # apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YuhangChen1/HUST_OPEN_SOURCE
  # analytics:
  #   provider: google
  #   property: G-KJB4RXSKZG

nav:
  - 前言: "index.md"
  - 如何使用: "使用指南.md"
  - 通识课:
      - "前言": "通识课程/index.md"
      - "微积分 ":
          - "微积分上": "通识课程/calculus1.md"
          - "微积分下": "通识课程/calculus2.md"
      - "大学物理 ":
          - "大学物理1": "通识课程/physics1.md"
          - "大学物理2": "通识课程/physics2.md"
          - "大学物理实验": "通识课程/physics_experiment.md"
      - "电路 ":
          - "电路理论—非电气学院": "通识课程/circuit.md"
      - "概率论 ":
          - "概率论": "通识课程/probability.md"
      - "线性代数 ":
          - "线性代数": "通识课程/linear_algebra.md"
      - "中国语文 ":
          - "中国语文": "通识课程/Chinese.md"
      - "综合英语 ":
          - "综合英语": "通识课程/English1.md"
      - "思想道德与法治 ":
          - "思想道德与法治": "通识课程/Ideological.md"
      - "思政课社会实践 ":
          - "思政课社会实践": "通识课程/Ideological_pratice.md"
      - "启明学院一元分析 ":
          - "启明学院一元分析": "通识课程/qiming_colleage_special.md"
          
  - 计算机学院:
      - "前言": "计算机学院/index.md"
      - "C语言 ": "计算机学院/c.md"
      - "程序设计": "计算机学院/c_design.md" 
      - "新生实践课": "计算机学院/pratice.md"
      - "计算思维": "计算机学院/computational_thinking.md"
  - 生命科学与技术学院:
      - "前言": "生命科学与技术学院/index.md"
      - "微生物学 (Microbiology)": "生命科学与技术学院/microbiology.md"

  