site_name: HUST开源计划
site_url: https://csdiy.wiki/
site_author: Francis_Chen
site_description: >-
  HUST开源计划

repo_name: HUST_OPEN_SOURCE
repo_url: https://github.com/YuhangChen1/HUST_OPEN_SOURCE

copyright: Copyright &copy; 2025-present <a href="https://github.com/YuhangChen1/" target="_blank" rel="noopener noreferrer">YuhangChen1/a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pkuflyingpig/cs-self-learning/
  analytics:
    provider: google
    property: G-KJB4RXSKZG

nav:
  - 前言: "index.md"
  - 如何使用: "使用指南.md"
  # - 必学工具:
  #     - 翻墙: "必学工具/翻墙.md"
  #     - Vim: "必学工具/Vim.md"
  #     - Emacs: "必学工具/Emacs.md"
  #     - Git: "必学工具/Git.md"
  #     - GitHub: "必学工具/GitHub.md"
  #     - "GNU Make": "必学工具/GNU_Make.md"
  #     - CMake: "必学工具/CMake.md"
  #     - LaTeX: "必学工具/LaTeX.md"
  #     - Docker: "必学工具/Docker.md"
  #     - Scoop: "必学工具/Scoop.md"
  #     - 日常学习工作流: "必学工具/workflow.md"
  #     - 实用工具箱: "必学工具/tools.md"
  #     - 毕业论文: "必学工具/thesis.md"
  #     - 信息检索: "必学工具/信息检索.md"
  # - 好书推荐: "好书推荐.md"
  - 通识课:
      - "前言": "通识课程/index.md"
      - "微积分 (Calculus)":
          - "微积分上": "通识课程/calculus1.md"
          - "微积分下": "通识课程/calculus2.md"
      - "大学物理 (University Physics)":
          - "大学物理1": "通识课程/physics1.md"
          - "大学物理2": "通识课程/physics2.md"
          - "大学物理实验1": "通识课程/physics_experiment1.md"
          - "大学物理实验2": "通识课程/physics_experiment2.md"
      - "电路 (Circuits)":
          - "电路理论—非电气学院": "通识课程/circuit.md"
      - "概率论 (Probability Theory)":
          - "概率论": "通识课程/probability.md"
  